url: 'https://helmilyn.github.io'
baseurl: ''
title: 'Helmilyn Design'
plugins:
  - jekyll-postcss
postcss:
  cache: false
collections_dir: _portfolio
collections:
  ui-ux-design:
    output: true
    permalink: /:collection/:name
    sort_by: custom_order
  graphic-design:
    output: true
    permalink: /:collection/:name
    sort_by: custom_order
  illustration:
    output: false
include:
  - _pages
exclude:
  - package.json
  - package-lock.json
  - pnpm-lock.yaml
  - '*.config.js'
  - '*.txt'
